task:
  name: Build FreeBSD port--
  freebsd_instance:
  setup_script:
    - pkg install -y git
    - git clone https://git.FreeBSD.org/ports.git /usr/ports
  build_script:
  - mkdir -p /usr/ports/www/py-django-jinja
  - cp -R py-django-jinja/* /usr/ports/www/py-django-jinja/
  - cd /usr/ports/www/py-django-jinja
  - make install clean
